use crate::core::config::load_config;
use crate::core::db;
use crate::core::event::{AppEvent, EventBus};
use crate::core::parser::parse_output;
use crate::core::state::{get_findings_internal, AppState};
use crate::core::tools::{detect_tool, render_args, suggest_tools};
use crate::core::types::{Finding, ScanRequest, Session, ToolProfile, TOROT_VERSION};
use crate::core::report::render_report;
use crate::core::parser::summarize_findings;
use crate::util::time::now_unix;
use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::sync::Arc;
use std::time::Duration;
use tokio::io::{AsyncBufReadExt, BufReader};
use tokio::process::Command as TokioCommand;
use tokio::task::JoinHandle;
